import React, { useEffect, useMemo, useState } from 'react';
import { Camera, Check, Edit3, Package, Settings, ShieldCheck, Star, User, X } from 'lucide-react';
import RentoraButton from '../components/ui/RentoraButton';
import RentoraCard from '../components/ui/RentoraCard';
import RentoraEmptyState from '../components/ui/RentoraEmptyState';
import { useLanguage } from '../context/LanguageContext';
import { usePiAuth } from '../context/PiAuthContext';
import { useRentora } from '../context/RentoraContext';

export default function ProfileRedesign({ onNavigate, onSelectItem }) {
  const { dir, t, l } = useLanguage();
  const { currentUser, isAuthenticated, setAuthModalOpen, updateUserProfile } = usePiAuth();
  const { items = [], fetchUserReviews } = useRentora();
  const [editing, setEditing] = useState(false), [displayName, setDisplayName] = useState(''), [bio, setBio] = useState(''), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false), [reviews, setReviews] = useState(null);

  useEffect(() => {
    setDisplayName(currentUser?.displayName || currentUser?.username || '');
    setBio(currentUser?.bio || '');
    if (currentUser?.uid || currentUser?.username) fetchUserReviews(currentUser.uid || currentUser.username).then(setReviews).catch(() => setReviews({ stats: {}, reviews: [] }));
  }, [currentUser?.uid, currentUser?.username]);

  const mine = useMemo(() => {
    const uid = String(currentUser?.uid || ''), username = String(currentUser?.username || '').replace('@', '').toLowerCase();
    return items.filter(i => (uid && String(i.ownerUid || '') === uid) || (username && String(i.ownerUsername || '').replace('@', '').toLowerCase() === username));
  }, [items, currentUser]);

  if (!isAuthenticated) return <main dir={dir} className="mx-auto w-full max-w-xl px-3 py-10"><RentoraCard className="p-6 text-center"><div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-rentora-panel bg-rentora-primary-soft text-rentora-primary"><User size={25}/></div><h1 className="text-xl font-black text-rentora-ink">{t('profileTitle')}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{l('برای مشاهده و مدیریت پروفایل وارد شوید.','Sign in to view and manage your profile.','سجل الدخول لإدارة ملفك الشخصي.','登录以查看和管理个人资料。')}</p><RentoraButton className="mt-5" onClick={() => setAuthModalOpen(true)}>{t('navLogin')}</RentoraButton></RentoraCard></main>;

  const save = async () => { setSaving(true); setSaved(false); try { await updateUserProfile?.({ displayName: displayName.trim(), bio: bio.trim() }); setSaved(true); setEditing(false); } finally { setSaving(false); } };

  return <main dir={dir} className="mx-auto w-full max-w-4xl space-y-4 px-3 pb-32 pt-2 sm:px-5 sm:pb-10">
    <header className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-rentora-primary">{l('حساب من','My account','حسابي','我的账户')}</p><h1 className="text-2xl font-black text-rentora-ink">{t('profileTitle')}</h1></div><RentoraButton variant="secondary" size="sm" onClick={() => setEditing(v => !v)} aria-pressed={editing}>{editing ? <X size={15}/> : <Edit3 size={15}/>} {editing ? l('لغو','Cancel','إلغاء','取消') : l('ویرایش','Edit','تعديل','编辑')}</RentoraButton></header>
    <RentoraCard className="overflow-hidden"><div className="bg-rentora-primary-soft p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative shrink-0">{currentUser?.avatar ? <img src={currentUser.avatar} alt="" className="h-24 w-24 rounded-rentora-panel border-4 border-rentora-surface object-cover shadow-rentora-card"/> : <div className="h-24 w-24 rounded-rentora-panel border-4 border-rentora-surface bg-rentora-primary-soft shadow-rentora-card" aria-hidden="true" />}<span className="absolute -bottom-1 -right-1 flex h-8 w-8 items-center justify-center rounded-full border-2 border-rentora-surface bg-rentora-primary text-white"><Camera size={14}/></span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl font-black text-rentora-ink">{displayName || currentUser?.username}</h2>{currentUser?.kycStatus === 'verified' && <span className="inline-flex items-center gap-1 rounded-rentora-pill bg-rentora-success-soft px-2 py-1 text-xs font-bold text-rentora-success"><ShieldCheck size={13}/>{t('badgeKycVerified')}</span>}</div><p className="mt-1 text-sm text-slate-500" dir="ltr">@{currentUser?.username || 'pioneer'}</p>{bio && <p className="mt-3 text-sm leading-6 text-slate-600">{bio}</p>}</div></div></div>{editing && <div className="grid gap-3 p-5"><label className="text-xs font-bold"> {l('نام نمایشی','Display name','الاسم الظاهر','显示名称')}<input value={displayName} onChange={e=>setDisplayName(e.target.value)} className="mt-1 min-h-11 w-full rounded-rentora-control border border-rentora-border bg-rentora-surface px-3 text-sm outline-none focus:ring-2 focus:ring-rentora-primary-accent"/></label><label className="text-xs font-bold">{l('معرفی کوتاه','Bio','نبذة','简介')}<textarea value={bio} onChange={e=>setBio(e.target.value)} rows={3} className="mt-1 w-full rounded-rentora-control border border-rentora-border bg-rentora-surface px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-rentora-primary-accent"/></label><RentoraButton onClick={save} disabled={saving}>{saving ? l('در حال ذخیره...','Saving...','جار الحفظ...','正在保存...') : <><Check size={15}/>{l('ذخیره تغییرات','Save changes','حفظ التغييرات','保存更改')}</>}</RentoraButton></div>}</RentoraCard>
    {saved && <div role="status" className="flex items-center gap-2 rounded-rentora-control bg-rentora-success-soft px-3 py-2 text-sm font-bold text-rentora-success"><Check size={16}/>{l('پروفایل ذخیره شد.','Profile saved.','تم حفظ الملف.','资料已保存。')}</div>}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-3"><RentoraCard className="p-4"><Package className="text-rentora-primary" size={18}/><strong className="mt-2 block text-xl">{mine.length}</strong><span className="text-xs text-slate-500">{t('profileMyListings')}</span></RentoraCard><RentoraCard className="p-4"><Star className="text-amber-500" size={18} fill="currentColor"/><strong className="mt-2 block text-xl">{reviews?.stats?.averageRating ?? '—'}</strong><span className="text-xs text-slate-500">{t('profileRating')}</span></RentoraCard><RentoraCard className="col-span-2 p-4 sm:col-span-1"><ShieldCheck className="text-rentora-success" size={18}/><strong className="mt-2 block text-xl">{reviews?.stats?.totalReviews ?? 0}</strong><span className="text-xs text-slate-500">{t('profileReviews')}</span></RentoraCard></section>
    <RentoraCard className="p-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-black text-rentora-ink">{t('profileMyListings')}</h2><RentoraButton variant="ghost" size="sm" onClick={()=>onNavigate('owner-hub')}><Settings size={15}/>{l('مدیریت','Manage','إدارة','管理')}</RentoraButton></div>{mine.length===0 ? <RentoraEmptyState title={l('هنوز آگهی‌ای ندارید','No listings yet','لا توجد إعلانات بعد','暂无物品')} description={l('اولین وسیله خود را برای اجاره ثبت کنید.','Create your first rental listing.','أنشئ أول إعلان تأجير.','创建您的第一个出租物品。')} action={<RentoraButton size="sm" onClick={()=>onNavigate('list-item')}>{l('ثبت آگهی','List an item','إضافة إعلان','发布物品')}</RentoraButton>}/> : <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-3">{mine.slice(0,6).map(item=><button key={item.id} type="button" onClick={()=>onSelectItem(item)} className="overflow-hidden rounded-rentora-control border border-rentora-border text-start focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rentora-primary-accent"><div className="aspect-square bg-slate-100">{item.images?.[0] ? <img src={item.images[0]} alt="" className="h-full w-full object-cover"/> : <div className="h-full w-full bg-rentora-primary-soft"/>}</div><div className="p-2"><strong className="block truncate text-xs">{item.title}</strong><span className="text-[11px] text-slate-500">{item.pricePerDay || item.price_per_day || '—'} π</span></div></button>)}</div>}</RentoraCard>
  </main>;
}
